backend/core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
	path("", views.HomeView.as_view(), name="home"),
    path("generate-logo/", views.GenerateLogoView.as_view(), name="generate-logo"),
]

backend/django_chatgpt/urls.py
# --------------------------------------------------------------
# Django imports
# --------------------------------------------------------------
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace="core")),
]

if settings.DEBUG == 1:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/core/forms/input.py
# --------------------------------------------------------------
# Django imports
# --------------------------------------------------------------
from django import forms


class InputForm(forms.Form):
    '''
    Basic form for our animal name suggestion form and logo generator form
    '''

    input = forms.CharField(max_length=100, required=True,
      widget=forms.TextInput(attrs={
        'placeholder': 'Give me something to work on...'}))

    class Meta:
        fields = ('input',)

backend/core/views/generate_image.py
# --------------------------------------------------------------
# Django imports
# --------------------------------------------------------------
from django.views import generic
from django.utils.decorators import method_decorator
from django.http import JsonResponse
from django.conf import settings

# --------------------------------------------------------------
# App imports
# --------------------------------------------------------------
from core.forms import AnimalForm

# --------------------------------------------------------------
# Project imports
# --------------------------------------------------------------
from utils.decorators import ajax_required
from utils.mixins import FormErrors

# --------------------------------------------------------------
# 3rd Party imports
# --------------------------------------------------------------
import openai

openai.api_key = settings.OPENAI_API_KEY

class GenerateImageView(generic.FormView):
    """
    FormView used for our generate image page.

    **Template:**

    :template:`generate_image.html`
    """
    template_name = "generate_image.html"
    form_class = AnimalForm
    success_url = "/"

    def generate_prompt(self, breed):
        return 'Suggest three names for an animal that is a superhero.'

    @method_decorator(ajax_required)
    def post(self, request,*args, **kwargs):
        data = {'result': 'Error', 'message': "Something went wrong, please try again", "redirect": False, "data":None}
        form = AnimalForm(request.POST)
        if form.is_valid():

            breed = form.cleaned_data.get("breed")

            response = openai.Image.create(
                prompt=breed,
                n=1,
                size="1024x1024"
            )
            print(response)
            print(response['data'][0]['url'])
            data.update({
                'result': "Success",
                'message': "ChatGPT has created this image",
                'data': response['data'][0]['url']
            })
            return JsonResponse(data)

        else:
            data["message"] = FormErrors(form)
            return JsonResponse(data, status=400)

backend/core/views/generate_logo.py
# --------------------------------------------------------------
# Django imports
# --------------------------------------------------------------
from django.views import generic
from django.utils.decorators import method_decorator
from django.http import JsonResponse
from django.conf import settings

# --------------------------------------------------------------
# App imports
# --------------------------------------------------------------
from core.forms import InputForm

# --------------------------------------------------------------
# Project imports
# --------------------------------------------------------------
from utils.decorators import ajax_required
from utils.mixins import FormErrors

# --------------------------------------------------------------
# 3rd Party imports
# --------------------------------------------------------------
import openai

openai.api_key = settings.OPENAI_API_KEY

class GenerateLogoView(generic.FormView):
    """
    FormView used for our generate logo page.

    **Template:**

    :template:`generate_logo.html`
    """
    template_name = "generate_logo.html"
    form_class = InputForm
    success_url = "/"

    @method_decorator(ajax_required)
    def post(self, request,*args, **kwargs):
        data = {'result': 'Error', 'message': "Something went wrong, please try again", "redirect": False, "data":None}
        form = InputForm(request.POST)
        if form.is_valid():

            input = form.cleaned_data.get("input")

            response = openai.Image.create(
                prompt=input,
                n=1,
                size="1024x1024"
            )
            data.update({
                'result': "Success",
                'message': "ChatGPT has created this logo",
                'data': response['data'][0]['url']
            })
            return JsonResponse(data)

        else:
            data["message"] = FormErrors(form)
            return JsonResponse(data, status=400)

backend/core/views/home.py
# --------------------------------------------------------------
# Django imports
# --------------------------------------------------------------
from django.views import generic
from django.utils.decorators import method_decorator
from django.http import JsonResponse
from django.conf import settings

# --------------------------------------------------------------
# App imports
# --------------------------------------------------------------
from core.forms import InputForm

# --------------------------------------------------------------
# Project imports
# --------------------------------------------------------------
from utils.decorators import ajax_required
from utils.mixins import FormErrors

# --------------------------------------------------------------
# 3rd Party imports
# --------------------------------------------------------------
import openai

openai.api_key = settings.OPENAI_API_KEY

class HomeView(generic.FormView):
    """
    FormView used for our home page.

    **Template:**

    :template:`index.html`
    """
    template_name = "index.html"
    form_class = InputForm
    success_url = "/"

    def generate_prompt(self, input):
        return f'Suggest three {input} animal names'

    @method_decorator(ajax_required)
    def post(self, request,*args, **kwargs):
        data = {'result': 'Error', 'message': "Something went wrong, please try again", "redirect": False, "data":None}
        form = InputForm(request.POST)
        if form.is_valid():

            input = form.cleaned_data.get("input")

            response = openai.Completion.create(
                model="text-davinci-003",
                prompt=self.generate_prompt(input),
                temperature=0.6,
            )
            data.update({
                'result': "Success",
                'message': "ChatGPT has suggested some names",
                'data': list(filter(None,response.choices[0].text.splitlines( )))
            })
            return JsonResponse(data)

        else:
            data["message"] = FormErrors(form)
            return JsonResponse(data, status=400)

backend/templates/generate_image.html
{% load static %}
<!DOCTYPE html>
<head>
  <title>Django ChatGPT demo</title>
  <link
    rel="shortcut icon"
    href="{% static 'dog.png' %}"
  />
  <link rel="stylesheet" href="{% static 'main.css' %}" />
</head>

<body>
  <img src="{% static 'dog.png' %}" class="icon" />
  <h3>Use AI to create an image</h3>
  <form action="{% url 'core:generate-image' %}" method="post" id="basicimageform">
    {% csrf_token %}
    {{form.breed}}
    <button type="submit" >Generate image</button>
  </form>

  <div class="result">

  </div>

  <script src="{% static 'jquery-3.5.1.min.js' %}"></script>
  <script src="{% static 'custom.js' %}"></script>
</body>

backend/templates/generate_logo.html
{% load static %}
<!DOCTYPE html>
<head>
  <title>Django ChatGPT demo</title>
  <link
    rel="shortcut icon"
    href="{% static 'dog.png' %}"
  />
  <link rel="stylesheet" href="{% static 'main.css' %}" />
</head>

<body>
  {% comment %} <img src="{% static 'dog.png' %}" class="icon" /> {% endcomment %}
  <h3>Use AI to create a logo</h3>
  <form action="{% url 'core:generate-logo' %}" method="post" id="basicimageform">
    {% csrf_token %}
    {{form.input}}
    <button type="submit" >Generate logo</button>
  </form>

  <div class="result">

  </div>

  <script src="{% static 'jquery-3.5.1.min.js' %}"></script>
  <script src="{% static 'main.js' %}"></script>
</body>

backend/templates/index.html
{% load static %}
<!DOCTYPE html>
<head>
  <title>Django ChatGPT demo</title>
  <link
    rel="shortcut icon"
    href="{% static 'dog.png' %}"
  />
  <link rel="stylesheet" href="{% static 'main.css' %}" />
</head>

<body>
  <img src="{% static 'dog.png' %}" class="icon" />
  <h3>Name my pet</h3>
  <form action="{% url 'core:home' %}" method="post" id="basicform">
    {% csrf_token %}
    {{form.input}}
    <button type="submit" >Generate names</button>
  </form>

  <div>
    <ul class="result">
    </ul>
  </div>

  <script src="{% static 'jquery-3.5.1.min.js' %}"></script>
  <script src="{% static 'main.js' %}"></script>
</body>